version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.19
    restart: always
    ports:
    - "4444:4444"
    environment:
      PRISMA_CONFIG: |
        port: 4444
        managementApiSecret: secretkeyvkouk1234
        databases:
          default:
            connector: postgres
            host: postgres-db
            port: 5432
            user: vkouk
            password: smartlogger
            migrations: true
  postgres-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: vkouk
      POSTGRES_PASSWORD: smartlogger
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: